apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: webapp-secret-provider
  namespace: webapp
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/webapp/mysql/writer" # SecretManager に設定した「シークレットの名前」の値
        objectType: "secretsmanager"
        jmesPath:
          # Secrets Manager で管理している値の `username` フィールドを `username` という名前でエイリアス
          - path: "username"
            objectAlias: username
          # Secrets Manager で管理している値の `password` フィールドを `username` という名前でエイリアス
          - path: "password"
            objectAlias: password
  secretObjects:
    - secretName: webapp-secret # Kubernetes 内で作成される Secret の名前
      type: Opaque
      data:
        - key: db.user
          objectName: username # `username` エイリアスからデータを取得
        - key: db.pass
          objectName: password # `password` エイリアスからデータを取得

