name: 'Enable auto-merge'
description: ''
inputs:
  branch:
    description: 'Branch'
    required: true
    default: ''
  approver-github-token:
    description: 'Approver GitHub Token'
    required: true
  merge-operator-github-token:
    description: 'Merge operator GitHub Token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        ref: ${{ inputs.branch }}

    - name: Approve the pull request
      shell: bash
      run: gh pr review --approve ${{ github.event.pull_request.number }}
      env: 
        GITHUB_TOKEN: ${{ inputs.approver-github-token }} # is different from ${{ inputs.github-token }}

    - name: Enable the auto-merge feature # to automatically merge the pull request when the checks pass.
      shell: bash
      run: | 
        # The auto-merge (--auto) settings are for users who want to use branch protection (Team or Enterprise plan).
        # gh pr merge --merge --delete-branch --auto ${{ github.event.pull_request.number }}
        
        # WARNING: It will merge without waiting for the workflow that performs lint checking on manifests.
        gh pr merge --merge --delete-branch ${{ github.event.pull_request.number }}
      env: 
        GITHUB_TOKEN: ${{ inputs.merge-operator-github-token }}
