name: 'Kubernetes Manifests Lint Check'
description: ''

inputs:
  branch:
    description: 'Branch'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    with:
      ref: ${{ inputs.branch }}

  - name: Install tools
    uses: asdf-vm/actions/install@v3

  - name: Lint manifests
    shell: bash
    run: ${{ github.action_path }}/lint.sh

