name: 'Kubernetes Manifests Lint Check'
description: ''

inputs:
  branch:
    description: 'Branch'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      ref: ${{ inputs.branch }}

  - name: Install tools
    uses: asdf-vm/actions/install@v3

  - name: Lint manifests (Kubernetes 1.30.0)
    shell: bash
    run: ${{ github.action_path }}/lint.sh 1.30.0

