name: Kubernetes Manifests Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install tools
      uses: asdf-vm/actions/install@v3

    - name: Lint manifests
      run: ./tools/lint.sh
