name: Kubernetes Manifests Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin/

    - name: Install kubeconform
      run: |
        curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xvz
        sudo mv kubeconform /usr/local/bin/

    - name: Lint Dev Manifests with kubeconform
      run: |
        kustomize build ./manifests/overlays/dev > output-dev.yaml
        kubeconform output-dev.yaml

    - name: Lint Prod Manifests with kubeconform
      run: |
        kustomize build ./manifests/overlays/prod > output-prod.yaml
        kubeconform -skip SecretProviderClass output-prod.yaml

        # https://github.com/yannh/kubeconform#customresourcedefinition-crd-support
        # https://github.com/datreeio/CRDs-catalog/tree/main/secrets-store.csi.x-k8s.io
        kubeconform \
          -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/secrets-store.csi.x-k8s.io/secretproviderclass_v1.json \
          ./manifests/overlays/prod/secret-provider-class.yaml

